# Configuração do Prometheus
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Regras de alertas
rule_files:
  - "rules/*.yml"

# Configuração de alertas
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuração de scraping
scrape_configs:
  # Métricas do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas da aplicação
  - job_name: 'devops-platform'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/api/metrics/prometheus'
    scrape_interval: 10s

  # Métricas do sistema (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Métricas de containers (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Métricas do PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Métricas do Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Métricas do Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Blackbox monitoring para health checks
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api:3000/api/health
        - https://your-domain.com/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
